import {
  Department,
  Teacher,
  Subject,
  Student,
  AttendanceRecord,
  SmsLog,
  ClassCoordinatorAssignment,
  TeacherSubject,
  UserAccount,
  Notice,
  AcademicClass,
} from "./types";

export const mockUsers: UserAccount[] = [
  {
    id: "admin-1",
    full_name: "Dr. Arthur Pendelton",
    email: "admin@edutrack.edu",
    role: "admin",
    status: "active",
  },
  {
    id: "hod-user-id",
    full_name: "Dr. Robert Vance",
    email: "hod.cse@edutrack.edu",
    role: "hod",
    department_id: "dept-1",
    status: "active",
  },
  {
    id: "cc-user-id",
    full_name: "Prof. Emily Watson",
    email: "cc@edutrack.edu",
    role: "class_coordinator",
    department_id: "dept-1",
    teacher_id: "t-4",
    status: "active",
  },
];

export const mockNotices: Notice[] = [];

export const mockClasses: AcademicClass[] = [
  {
    id: "class-cse-fe",
    name: "FE CSE-A",
    department_id: "dept-1",
    year: 1,
    semester: 1,
    coordinator_teacher_id: "t-5",
    status: "active",
  },
  {
    id: "class-cse-se-a",
    name: "SE CSE-A",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    coordinator_teacher_id: "t-2",
    status: "active",
  },
  {
    id: "class-cse-se-b",
    name: "SE CSE-B",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    coordinator_teacher_id: "t-2",
    status: "active",
  },
  {
    id: "class-cse-te-a",
    name: "TE CSE-A",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    coordinator_teacher_id: "t-4",
    status: "active",
  },
  {
    id: "class-cse-te-b",
    name: "TE CSE-B",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    coordinator_teacher_id: "t-4",
    status: "active",
  },
  {
    id: "class-cse-be-a",
    name: "BE CSE-A",
    department_id: "dept-1",
    year: 4,
    semester: 7,
    coordinator_teacher_id: null,
    status: "active",
  },
];

export const mockDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Computer Science & Engineering",
    code: "CSE",
    hod_id: "t-1",
    status: "active",
  },
  {
    id: "dept-2",
    name: "Electronics & Communication",
    code: "ECE",
    hod_id: "t-3",
    status: "active",
  },
  {
    id: "dept-3",
    name: "Information Technology",
    code: "IT",
    hod_id: "t-4",
    status: "active",
  },
  {
    id: "dept-4",
    name: "Mechanical Engineering",
    code: "MECH",
    status: "inactive",
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "t-1",
    employee_id: "EMP-101",
    full_name: "Dr. Robert Vance (HOD)",
    email: "hod.cse@edutrack.edu",
    mobile: "9876543201",
    department_id: "dept-1",
    user_id: "hod-user-id",
    role: "hod",
    status: "active",
    designation: "Professor & Head of Department",
    qualification: "Ph.D in Computer Science & Engineering",
    date_of_birth: "1978-06-15",
    experience_years: "18 Years",
  },
  {
    id: "t-2",
    employee_id: "EMP-102",
    full_name: "Prof. Sarah Jenkins",
    email: "s.jenkins@edutrack.edu",
    mobile: "9876543202",
    department_id: "dept-1",
    user_id: "teacher-user-id",
    is_class_coordinator: true,
    assigned_year: 2,
    assigned_semester: 3,
    role: "class_coordinator",
    status: "active",
    designation: "Associate Professor & SE Coordinator",
    qualification: "M.Tech in Software Systems",
    date_of_birth: "1985-09-24",
    experience_years: "11 Years",
  },
  {
    id: "t-3",
    employee_id: "EMP-103",
    full_name: "Dr. Alan Turing (HOD)",
    email: "a.turing@edutrack.edu",
    mobile: "9876543203",
    department_id: "dept-2",
    user_id: null,
    role: "hod",
    status: "active",
    designation: "Professor & Head of Department",
    qualification: "Ph.D in Artificial Intelligence",
    date_of_birth: "1980-04-12",
    experience_years: "15 Years",
  },
  {
    id: "t-4",
    employee_id: "EMP-104",
    full_name: "Prof. Emily Watson",
    email: "e.watson@edutrack.edu",
    mobile: "9876543204",
    department_id: "dept-1",
    user_id: "cc-user-id",
    is_class_coordinator: true,
    assigned_year: 3,
    assigned_semester: 5,
    role: "class_coordinator",
    status: "active",
    designation: "Assistant Professor & TE Coordinator",
    qualification: "M.Tech in Cyber Security",
    date_of_birth: "1990-11-08",
    experience_years: "7 Years",
  },
  {
    id: "t-5",
    employee_id: "EMP-105",
    full_name: "Prof. David Miller",
    email: "d.miller@edutrack.edu",
    mobile: "9876543205",
    department_id: "dept-1",
    user_id: null,
    is_class_coordinator: false,
    role: "lecturer",
    status: "active",
    designation: "Assistant Professor",
    qualification: "M.Tech in Computer Engineering",
    date_of_birth: "1992-03-18",
    experience_years: "5 Years",
  },
];

export const mockClassCoordinatorAssignments: ClassCoordinatorAssignment[] = [
  {
    id: "cca-1",
    teacher_id: "t-2",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    class_id: "class-cse-se-a",
    class_name: "SE CSE-A",
    assigned_by: "hod-user-id",
  },
  {
    id: "cca-1-b",
    teacher_id: "t-2",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    class_id: "class-cse-se-b",
    class_name: "SE CSE-B",
    assigned_by: "hod-user-id",
  },
  {
    id: "cca-2",
    teacher_id: "t-4",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-a",
    class_name: "TE CSE-A",
    assigned_by: "hod-user-id",
  },
];

export const mockSubjects: Subject[] = [
  // 1st Year (FE) - Parallel Sem 1
  {
    id: "sub-fe-1",
    code: "CS101",
    name: "Engineering Mathematics I",
    department_id: "dept-1",
    year: 1,
    semester: 1,
    credits: 4,
  },
  {
    id: "sub-fe-2",
    code: "CS102",
    name: "Programming for Problem Solving in C",
    department_id: "dept-1",
    year: 1,
    semester: 1,
    credits: 4,
  },
  // 2nd Year (SE) - Parallel Sem 3 (2nd Year 1st Sem)
  {
    id: "sub-se-1",
    code: "CS301",
    name: "Data Structures & Algorithms",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    credits: 4,
  },
  {
    id: "sub-se-2",
    code: "CS302",
    name: "Digital Electronics & Logic Design",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    credits: 3,
  },
  // 3rd Year (TE) - Parallel Sem 5 (3rd Year 1st Sem)
  {
    id: "sub-te-1",
    code: "CS501",
    name: "Design and Analysis of Algorithms",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    credits: 4,
  },
  {
    id: "sub-te-2",
    code: "CS502",
    name: "Database Management Systems",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    credits: 4,
  },
  {
    id: "sub-te-3",
    code: "CS503",
    name: "Computer Networks",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    credits: 3,
  },
  {
    id: "sub-te-4",
    code: "CS504",
    name: "Operating Systems",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    credits: 3,
  },
  // 4th Year (BE) - Parallel Sem 7 (4th Year 1st Sem)
  {
    id: "sub-be-1",
    code: "CS701",
    name: "Cloud Computing & DevOps",
    department_id: "dept-1",
    year: 4,
    semester: 7,
    credits: 4,
  },
  {
    id: "sub-be-2",
    code: "CS702",
    name: "Machine Learning & Artificial Intelligence",
    department_id: "dept-1",
    year: 4,
    semester: 7,
    credits: 4,
  },
];

export const mockTeacherSubjects: TeacherSubject[] = [
  // HOD (Dr. Robert Chen - t-1) teaches multiple classes across years (BE and TE Divisions)
  { id: "ts-1", teacher_id: "t-1", subject_id: "sub-be-1", class_name: "BE CSE-A", class_id: "class-cse-be-a", year: 4, semester: 7 },
  { id: "ts-2", teacher_id: "t-1", subject_id: "sub-te-1", class_name: "TE CSE-A", class_id: "class-cse-te-a", year: 3, semester: 5 },
  { id: "ts-3", teacher_id: "t-1", subject_id: "sub-te-1", class_name: "TE CSE-B", class_id: "class-cse-te-b", year: 3, semester: 5 },

  // Class Coordinator (Prof. Sarah Jenkins - t-2, SE Coordinator) teaches multiple classes (both SE Div A & B, plus FE)
  { id: "ts-4", teacher_id: "t-2", subject_id: "sub-se-1", class_name: "SE CSE-A", class_id: "class-cse-se-a", year: 2, semester: 3 },
  { id: "ts-5", teacher_id: "t-2", subject_id: "sub-se-1", class_name: "SE CSE-B", class_id: "class-cse-se-b", year: 2, semester: 3 },
  { id: "ts-6", teacher_id: "t-2", subject_id: "sub-fe-2", class_name: "FE CSE-A", class_id: "class-cse-fe", year: 1, semester: 1 },

  // Class Coordinator (Prof. Emily Watson - t-4, TE Coordinator) teaches multiple classes (both TE Div A & B)
  { id: "ts-7", teacher_id: "t-4", subject_id: "sub-te-2", class_name: "TE CSE-A", class_id: "class-cse-te-a", year: 3, semester: 5 },
  { id: "ts-8", teacher_id: "t-4", subject_id: "sub-te-2", class_name: "TE CSE-B", class_id: "class-cse-te-b", year: 3, semester: 5 },

  // Lecturer (Prof. David Miller - t-5) teaches multiple classes (FE and both SE divisions)
  { id: "ts-9", teacher_id: "t-5", subject_id: "sub-fe-2", class_name: "FE CSE-A", class_id: "class-cse-fe", year: 1, semester: 1 },
  { id: "ts-10", teacher_id: "t-5", subject_id: "sub-se-2", class_name: "SE CSE-A", class_id: "class-cse-se-a", year: 2, semester: 3 },
  { id: "ts-11", teacher_id: "t-5", subject_id: "sub-se-2", class_name: "SE CSE-B", class_id: "class-cse-se-b", year: 2, semester: 3 },
];

export const mockStudents: Student[] = [
  // 1st Year (FE) Students - Sem 1
  {
    id: "st-fe-1",
    roll_number: "24CS001",
    reg_number: "REG-2024-001",
    full_name: "Aarav Sharma",
    department_id: "dept-1",
    year: 1,
    semester: 1,
    class_id: "class-cse-fe",
    class_name: "FE CSE-A",
    parent_name: "Rajesh Sharma",
    parent_mobile: "9876543220",
    student_mobile: "9876543221",
    email: "aarav.s@student.college.edu",
    address: "Campus View Hostel A, Rm 101",
    date_of_birth: "2006-04-10",
    gender: "male",
    status: "active",
  },
  {
    id: "st-fe-2",
    roll_number: "24CS002",
    reg_number: "REG-2024-002",
    full_name: "Ananya Deshmukh",
    department_id: "dept-1",
    year: 1,
    semester: 1,
    class_id: "class-cse-fe",
    class_name: "FE CSE-A",
    parent_name: "Sanjay Deshmukh",
    parent_mobile: "9876543222",
    student_mobile: "9876543223",
    email: "ananya.d@student.college.edu",
    address: "Shastri Nagar, Green Valley",
    date_of_birth: "2006-07-19",
    gender: "female",
    status: "active",
  },

  // 2nd Year (SE) Students - Sem 3 (SE CSE-A and SE CSE-B)
  {
    id: "st-se-1",
    roll_number: "23CS001",
    reg_number: "REG-2023-001",
    full_name: "Rohan Kulkarni",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    class_id: "class-cse-se-a",
    class_name: "SE CSE-A",
    parent_name: "Mahesh Kulkarni",
    parent_mobile: "9876543230",
    student_mobile: "9876543231",
    email: "rohan.k@student.college.edu",
    address: "Block B, Pragati Apartments",
    date_of_birth: "2005-03-12",
    gender: "male",
    status: "active",
  },
  {
    id: "st-se-2",
    roll_number: "23CS002",
    reg_number: "REG-2023-002",
    full_name: "Pooja Patil",
    department_id: "dept-1",
    year: 2,
    semester: 3,
    class_id: "class-cse-se-b",
    class_name: "SE CSE-B",
    parent_name: "Anand Patil",
    parent_mobile: "9876543232",
    student_mobile: "9876543233",
    email: "pooja.p@student.college.edu",
    address: "Sector 9, College Road",
    date_of_birth: "2005-11-25",
    gender: "female",
    status: "active",
  },

  // 3rd Year (TE) Students - Sem 5 (TE CSE-A and TE CSE-B)
  {
    id: "st-1",
    roll_number: "22CS001",
    reg_number: "REG-2022-001",
    full_name: "Alexander Hayes",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-a",
    class_name: "TE CSE-A",
    parent_name: "Marcus Hayes",
    parent_mobile: "9876543210",
    student_mobile: "9876543211",
    email: "alex.h@student.college.edu",
    user_id: "student-user-id",
    address: "Flat 402, Campus View Residency, University Road",
    date_of_birth: "2004-05-15",
    gender: "male",
    status: "active",
  },
  {
    id: "st-2",
    roll_number: "22CS002",
    reg_number: "REG-2022-002",
    full_name: "Sophia Montgomery",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-a",
    class_name: "TE CSE-A",
    parent_name: "Elena Montgomery",
    parent_mobile: "9876543212",
    student_mobile: "9876543213",
    email: "sophia.m@student.college.edu",
    address: "456 University Blvd, Block C",
    date_of_birth: "2004-08-22",
    gender: "female",
    status: "active",
  },
  {
    id: "st-3",
    roll_number: "22CS003",
    reg_number: "REG-2022-003",
    full_name: "Ethan Gallagher",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-b",
    class_name: "TE CSE-B",
    parent_name: "David Gallagher",
    parent_mobile: "9876543214",
    student_mobile: "9876543215",
    email: "ethan.g@student.college.edu",
    address: "789 Academic Street, Hostel 3",
    date_of_birth: "2004-02-10",
    gender: "male",
    status: "active",
  },
  {
    id: "st-4",
    roll_number: "22CS004",
    reg_number: "REG-2022-004",
    full_name: "Isabella Rodriguez",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-b",
    class_name: "TE CSE-B",
    parent_name: "Carlos Rodriguez",
    parent_mobile: "9876543216",
    student_mobile: "9876543217",
    email: "isabella.r@student.college.edu",
    address: "321 Scholar Lane, North Campus",
    date_of_birth: "2004-11-30",
    gender: "female",
    status: "active",
  },
  {
    id: "st-5",
    roll_number: "22CS005",
    reg_number: "REG-2022-005",
    full_name: "Lucas Bennett",
    department_id: "dept-1",
    year: 3,
    semester: 5,
    class_id: "class-cse-te-a",
    class_name: "TE CSE-A",
    parent_name: "Arthur Bennett",
    parent_mobile: "9876543218",
    student_mobile: "9876543219",
    email: "lucas.b@student.college.edu",
    address: "555 Education Drive, City Center",
    date_of_birth: "2004-07-04",
    gender: "male",
    status: "active",
  },

  // 4th Year (BE) Students - Sem 7 (BE CSE-A)
  {
    id: "st-be-1",
    roll_number: "21CS001",
    reg_number: "REG-2021-001",
    full_name: "Vikramaditya Roy",
    department_id: "dept-1",
    year: 4,
    semester: 7,
    class_id: "class-cse-be-a",
    class_name: "BE CSE-A",
    parent_name: "Sunil Roy",
    parent_mobile: "9876543240",
    student_mobile: "9876543241",
    email: "vikram.r@student.college.edu",
    address: "Senior Hostel Block D, Room 304",
    date_of_birth: "2003-01-14",
    gender: "male",
    status: "active",
  },
];

export const mockAttendance: AttendanceRecord[] = [];
export const mockSmsLogs: SmsLog[] = [];

const today = new Date();
for (let i = 14; i >= 0; i--) {
  const d = new Date(today);
  d.setDate(today.getDate() - i);
  if (d.getDay() === 0 || d.getDay() === 6) continue;
  const dateStr = d.toISOString().split("T")[0];

  mockSubjects.forEach((sub) => {
    mockStudents.forEach((st) => {
      const isAbsent =
        (st.id === "st-3" && i % 3 === 0) || (st.id === "st-5" && i % 2 === 0);
      const status = isAbsent ? "absent" : "present";

      mockAttendance.push({
        id: `att-${sub.id}-${st.id}-${dateStr}`,
        student_id: st.id,
        subject_id: sub.id,
        date: dateStr,
        status,
        marked_by: "user-demo",
      });

      if (isAbsent && st.parent_mobile) {
        mockSmsLogs.push({
          id: `sms-${sub.id}-${st.id}-${dateStr}`,
          student_id: st.id,
          subject_id: sub.id,
          student_name: st.full_name,
          parent_mobile: st.parent_mobile,
          message: `Dear Parent,\n\nYour child, ${st.full_name}, was absent today (${dateStr}) for the subject "${sub.name}".\n\nPlease contact your child if required.\n\nThank you.`,
          status: "sent",
          attendance_date: dateStr,
          sent_at: `${dateStr}T10:30:00Z`,
        });
      }
    });
  });
}
