import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { college } from './college';

export interface PdfExportOptions {
  rows: Array<{
    roll: string;
    reg: string;
    name: string;
    subject: string;
    total: number;
    present: number;
    absent: number;
    percentage: number;
  }>;
  periodLabel: string;
  scopeLabel: string;
  yearLabel?: string;
  classLabel?: string;
  semesterLabel?: string;
  departmentLabel?: string;
  subjectLabel?: string;
  roleLabel?: string;
  fileName?: string;
}

export function exportAttendancePdf({
  rows,
  periodLabel,
  scopeLabel,
  yearLabel,
  classLabel,
  semesterLabel,
  departmentLabel,
  subjectLabel,
  roleLabel,
  fileName,
}: PdfExportOptions) {
  const doc = new jsPDF('p', 'mm', 'a4');

  // Header Banner
  doc.setFillColor(34, 76, 56);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(college.name, 14, 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`${college.tagline} · Official Academic Attendance Report`, 14, 19);

  // Metadata Box
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Academic & Scope Information', 14, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);

  // Left Column
  let currentY = 42;
  if (departmentLabel) {
    doc.text(`Department: ${departmentLabel}`, 14, currentY);
    currentY += 5.5;
  }
  if (yearLabel) {
    doc.text(`Engineering Year: ${yearLabel}`, 14, currentY);
    currentY += 5.5;
  }
  if (classLabel) {
    doc.text(`Class / Division: ${classLabel}`, 14, currentY);
    currentY += 5.5;
  }
  if (semesterLabel) {
    doc.text(`Semester: ${semesterLabel}`, 14, currentY);
    currentY += 5.5;
  }
  if (subjectLabel && subjectLabel !== '__all') {
    doc.text(`Subject: ${subjectLabel}`, 14, currentY);
    currentY += 5.5;
  }

  // Right Column
  let rightY = 42;
  doc.text(`Date Interval: ${periodLabel}`, 115, rightY);
  rightY += 5.5;
  doc.text(`Generated On: ${new Date().toLocaleString()}`, 115, rightY);
  rightY += 5.5;
  if (roleLabel) {
    doc.text(`Generated By Role: ${roleLabel}`, 115, rightY);
    rightY += 5.5;
  }
  doc.text(`Min Required Attendance: ${college.minAttendance}%`, 115, rightY);
  rightY += 5.5;
  doc.text(`Total Students In Report: ${rows.length}`, 115, rightY);

  const startTableY = Math.max(currentY, rightY) + 4;

  // Table Data
  const tableRows = rows.map((r) => [
    r.roll,
    r.reg || '—',
    r.name,
    r.subject,
    r.total.toString(),
    r.present.toString(),
    r.absent.toString(),
    `${r.percentage}%`,
  ]);

  autoTable(doc, {
    startY: startTableY,
    head: [['Roll No', 'Reg No', 'Student Name', 'Subject', 'Total', 'Present', 'Absent', 'Attendance %']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [34, 76, 56], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [248, 250, 248] },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 22 },
      2: { cellWidth: 42 },
      3: { cellWidth: 42 },
      4: { halign: 'right', cellWidth: 14 },
      5: { halign: 'right', cellWidth: 14 },
      6: { halign: 'right', cellWidth: 14 },
      7: { halign: 'right', fontStyle: 'bold', cellWidth: 22 },
    },
    didParseCell: function (data) {
      if (data.section === 'body' && data.column.index === 7) {
        const val = parseFloat(data.cell.raw as string);
        if (val < college.minAttendance) {
          data.cell.styles.textColor = [220, 38, 38];
        } else {
          data.cell.styles.textColor = [22, 101, 52];
        }
      }
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 14;

  // Signature Block
  if (finalY < 255) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(90, 90, 90);

    // 4 Signatures
    doc.line(14, finalY + 12, 54, finalY + 12);
    doc.text('Subject Teacher', 14, finalY + 16);

    doc.line(62, finalY + 12, 102, finalY + 12);
    doc.text('Class Coordinator (CC)', 62, finalY + 16);

    doc.line(110, finalY + 12, 150, finalY + 12);
    doc.text('Head of Dept (HOD)', 110, finalY + 16);

    doc.line(158, finalY + 12, 198, finalY + 12);
    doc.text('Principal / Dean', 158, finalY + 16);
  }

  const outputName =
    fileName ||
    `Attendance-Report-${(yearLabel || 'All').replace(/\s+/g, '_')}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(outputName);
}
